
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8881

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: system-service
        uri: lb://system-service/
        predicates:
          - Path=/system/**
        filters:
              - StripPrefix=1  #所有system请求转发到service-system
