eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /report/**
      serviceId: service-report
    api-b:
      path: /system/**
      serviceId: service-system


